public enum Country {

	AFG ("Afghanistan", "AF", "AFG"),
	ALB ("Albania", "AL", "ALB"),
	DZA ("Algeria", "DZ", "DZA"),
	ASM ("American Samoa", "AS", "ASM"),
	AND ("Andorra", "AD", "AND"),
	AGO ("Angola", "AO", "AGO"),
	AIA ("Anguilla", "AI", "AIA"),
	ATA ("Antarctica", "AQ", "ATA"),
	ATG ("Antigua and Barbuda", "AG", "ATG"),
	ARG ("Argentina", "AR", "ARG"),
	ARM ("Armenia", "AM", "ARM"),
	ABW ("Aruba", "AW", "ABW"),
	AUS ("Australia", "AU", "AUS"),
	AUT ("Austria", "AT", "AUT"),
	AZE ("Azerbaijan", "AZ", "AZE"),
	BHS ("Bahamas", "BS", "BHS"),
	BHR ("Bahrain", "BH", "BHR"),
	BGD ("Bangladesh", "BD", "BGD"),
	BRB ("Barbados", "BB", "BRB"),
	BLR ("Belarus", "BY", "BLR"),
	BEL ("Belgium", "BE", "BEL"),
	BLZ ("Belize", "BZ", "BLZ"),
	BEN ("Benin", "BJ", "BEN"),
	BMU ("Bermuda", "BM", "BMU"),
	BTN ("Bhutan", "BT", "BTN"),
	BOL ("Bolivia", "BO", "BOL"),
	BIH ("Bosnia and Herzegovina", "BA", "BIH"),
	BWA ("Botswana", "BW", "BWA"),
	BRA ("Brazil", "BR", "BRA"),
	IOT ("British Indian Ocean Territory", "IO", "IOT"),
	VGB ("British Virgin Islands", "VG", "VGB"),
	BRN ("Brunei", "BN", "BRN"),
	BGR ("Bulgaria", "BG", "BGR"),
	BFA ("Burkina Faso", "BF", "BFA"),
	BDI ("Burundi", "BI", "BDI"),
	KHM ("Cambodia", "KH", "KHM"),
	CMR ("Cameroon", "CM", "CMR"),
	CAN ("Canada", "CA", "CAN"),
	CPV ("Cape Verde", "CV", "CPV"),
	CYM ("Cayman Islands", "KY", "CYM"),
	CAF ("Central African Republic", "CF", "CAF"),
	TCD ("Chad", "TD", "TCD"),
	CHL ("Chile", "CL", "CHL"),
	CHN ("China", "CN", "CHN"),
	CXR ("Christmas Island", "CX", "CXR"),
	CCK ("Cocos Islands", "CC", "CCK"),
	COL ("Colombia", "CO", "COL"),
	COM ("Comoros", "KM", "COM"),
	COK ("Cook Islands", "CK", "COK"),
	CRI ("Costa Rica", "CR", "CRI"),
	HRV ("Croatia", "HR", "HRV"),
	CUB ("Cuba", "CU", "CUB"),
	CUW ("Curacao", "CW", "CUW"),
	CYP ("Cyprus", "CY", "CYP"),
	CZE ("Czech Republic", "CZ", "CZE"),
	COD ("Democratic Republic of the Congo", "CD", "COD"),
	DNK ("Denmark", "DK", "DNK"),
	DJI ("Djibouti", "DJ", "DJI"),
	DMA ("Dominica", "DM", "DMA"),
	DOM ("Dominican Republic", "DO", "DOM"),
	TLS ("East Timor", "TL", "TLS"),
	ECU ("Ecuador", "EC", "ECU"),
	EGY ("Egypt", "EG", "EGY"),
	SLV ("El Salvador", "SV", "SLV"),
	GNQ ("Equatorial Guinea", "GQ", "GNQ"),
	ERI ("Eritrea", "ER", "ERI"),
	EST ("Estonia", "EE", "EST"),
	ETH ("Ethiopia", "ET", "ETH"),
	FLK ("Falkland Islands", "FK", "FLK"),
	FRO ("Faroe Islands", "FO", "FRO"),
	FJI ("Fiji", "FJ", "FJI"),
	FIN ("Finland", "FI", "FIN"),
	FRA ("France", "FR", "FRA"),
	PYF ("French Polynesia", "PF", "PYF"),
	GAB ("Gabon", "GA", "GAB"),
	GMB ("Gambia", "GM", "GMB"),
	GEO ("Georgia", "GE", "GEO"),
	DEU ("Germany", "DE", "DEU"),
	GHA ("Ghana", "GH", "GHA"),
	GIB ("Gibraltar", "GI", "GIB"),
	GRC ("Greece", "GR", "GRC"),
	GRL ("Greenland", "GL", "GRL"),
	GRD ("Grenada", "GD", "GRD"),
	GUM ("Guam", "GU", "GUM"),
	GTM ("Guatemala", "GT", "GTM"),
	GGY ("Guernsey", "GG", "GGY"),
	GIN ("Guinea", "GN", "GIN"),
	GNB ("Guinea-Bissau", "GW", "GNB"),
	GUY ("Guyana", "GY", "GUY"),
	HTI ("Haiti", "HT", "HTI"),
	HND ("Honduras", "HN", "HND"),
	HKG ("Hong Kong", "HK", "HKG"),
	HUN ("Hungary", "HU", "HUN"),
	ISL ("Iceland", "IS", "ISL"),
	IND ("India", "IN", "IND"),
	IDN ("Indonesia", "ID", "IDN"),
	IRN ("Iran", "IR", "IRN"),
	IRQ ("Iraq", "IQ", "IRQ"),
	IRL ("Ireland", "IE", "IRL"),
	IMN ("Isle of Man", "IM", "IMN"),
	ISR ("Israel", "IL", "ISR"),
	ITA ("Italy", "IT", "ITA"),
	CIV ("Ivory Coast", "CI", "CIV"),
	JAM ("Jamaica", "JM", "JAM"),
	JPN ("Japan", "JP", "JPN"),
	JEY ("Jersey", "JE", "JEY"),
	JOR ("Jordan", "JO", "JOR"),
	KAZ ("Kazakhstan", "KZ", "KAZ"),
	KEN ("Kenya", "KE", "KEN"),
	KIR ("Kiribati", "KI", "KIR"),
	XKX ("Kosovo", "XK", "XKX"),
	KWT ("Kuwait", "KW", "KWT"),
	KGZ ("Kyrgyzstan", "KG", "KGZ"),
	LAO ("Laos", "LA", "LAO"),
	LVA ("Latvia", "LV", "LVA"),
	LBN ("Lebanon", "LB", "LBN"),
	LSO ("Lesotho", "LS", "LSO"),
	LBR ("Liberia", "LR", "LBR"),
	LBY ("Libya", "LY", "LBY"),
	LIE ("Liechtenstein", "LI", "LIE"),
	LTU ("Lithuania", "LT", "LTU"),
	LUX ("Luxembourg", "LU", "LUX"),
	MAC ("Macau", "MO", "MAC"),
	MKD ("Macedonia", "MK", "MKD"),
	MDG ("Madagascar", "MG", "MDG"),
	MWI ("Malawi", "MW", "MWI"),
	MYS ("Malaysia", "MY", "MYS"),
	MDV ("Maldives", "MV", "MDV"),
	MLI ("Mali", "ML", "MLI"),
	MLT ("Malta", "MT", "MLT"),
	MHL ("Marshall Islands", "MH", "MHL"),
	MRT ("Mauritania", "MR", "MRT"),
	MUS ("Mauritius", "MU", "MUS"),
	MYT ("Mayotte", "YT", "MYT"),
	MEX ("Mexico", "MX", "MEX"),
	FSM ("Micronesia", "FM", "FSM"),
	MDA ("Moldova", "MD", "MDA"),
	MCO ("Monaco", "MC", "MCO"),
	MNG ("Mongolia", "MN", "MNG"),
	MNE ("Montenegro", "ME", "MNE"),
	MSR ("Montserrat", "MS", "MSR"),
	MAR ("Morocco", "MA", "MAR"),
	MOZ ("Mozambique", "MZ", "MOZ"),
	MMR ("Myanmar", "MM", "MMR"),
	NAM ("Namibia", "NA", "NAM"),
	NRU ("Nauru", "NR", "NRU"),
	NPL ("Nepal", "NP", "NPL"),
	NLD ("Netherlands", "NL", "NLD"),
	ANT ("Netherlands Antilles", "AN", "ANT"),
	NCL ("New Caledonia", "NC", "NCL"),
	NZL ("New Zealand", "NZ", "NZL"),
	NIC ("Nicaragua", "NI", "NIC"),
	NER ("Niger", "NE", "NER"),
	NGA ("Nigeria", "NG", "NGA"),
	NIU ("Niue", "NU", "NIU"),
	PRK ("North Korea", "KP", "PRK"),
	MNP ("Northern Mariana Islands", "MP", "MNP"),
	NOR ("Norway", "NO", "NOR"),
	OMN ("Oman", "OM", "OMN"),
	PAK ("Pakistan", "PK", "PAK"),
	PLW ("Palau", "PW", "PLW"),
	PSE ("Palestine", "PS", "PSE"),
	PAN ("Panama", "PA", "PAN"),
	PNG ("Papua New Guinea", "PG", "PNG"),
	PRY ("Paraguay", "PY", "PRY"),
	PER ("Peru", "PE", "PER"),
	PHL ("Philippines", "PH", "PHL"),
	PCN ("Pitcairn", "PN", "PCN"),
	POL ("Poland", "PL", "POL"),
	PRT ("Portugal", "PT", "PRT"),
	PRI ("Puerto Rico", "PR", "PRI"),
	QAT ("Qatar", "QA", "QAT"),
	COG ("Republic of the Congo", "CG", "COG"),
	REU ("Reunion", "RE", "REU"),
	ROU ("Romania", "RO", "ROU"),
	RUS ("Russia", "RU", "RUS"),
	RWA ("Rwanda", "RW", "RWA"),
	BLM ("Saint Barthelemy", "BL", "BLM"),
	SHN ("Saint Helena", "SH", "SHN"),
	KNA ("Saint Kitts and Nevis", "KN", "KNA"),
	LCA ("Saint Lucia", "LC", "LCA"),
	MAF ("Saint Martin", "MF", "MAF"),
	SPM ("Saint Pierre and Miquelon", "PM", "SPM"),
	VCT ("Saint Vincent and the Grenadines", "VC", "VCT"),
	WSM ("Samoa", "WS", "WSM"),
	SMR ("San Marino", "SM", "SMR"),
	STP ("Sao Tome and Principe", "ST", "STP"),
	SAU ("Saudi Arabia", "SA", "SAU"),
	SEN ("Senegal", "SN", "SEN"),
	SRB ("Serbia", "RS", "SRB"),
	SYC ("Seychelles", "SC", "SYC"),
	SLE ("Sierra Leone", "SL", "SLE"),
	SGP ("Singapore", "SG", "SGP"),
	SXM ("Sint Maarten", "SX", "SXM"),
	SVK ("Slovakia", "SK", "SVK"),
	SVN ("Slovenia", "SI", "SVN"),
	SLB ("Solomon Islands", "SB", "SLB"),
	SOM ("Somalia", "SO", "SOM"),
	ZAF ("South Africa", "ZA", "ZAF"),
	KOR ("South Korea", "KR", "KOR"),
	SSD ("South Sudan", "SS", "SSD"),
	ESP ("Spain", "ES", "ESP"),
	LKA ("Sri Lanka", "LK", "LKA"),
	SDN ("Sudan", "SD", "SDN"),
	SUR ("Suriname", "SR", "SUR"),
	SJM ("Svalbard and Jan Mayen", "SJ", "SJM"),
	SWZ ("Swaziland", "SZ", "SWZ"),
	SWE ("Sweden", "SE", "SWE"),
	CHE ("Switzerland", "CH", "CHE"),
	SYR ("Syria", "SY", "SYR"),
	TWN ("Taiwan", "TW", "TWN"),
	TJK ("Tajikistan", "TJ", "TJK"),
	TZA ("Tanzania", "TZ", "TZA"),
	THA ("Thailand", "TH", "THA"),
	TGO ("Togo", "TG", "TGO"),
	TKL ("Tokelau", "TK", "TKL"),
	TON ("Tonga", "TO", "TON"),
	TTO ("Trinidad and Tobago", "TT", "TTO"),
	TUN ("Tunisia", "TN", "TUN"),
	TUR ("Turkey", "TR", "TUR"),
	TKM ("Turkmenistan", "TM", "TKM"),
	TCA ("Turks and Caicos Islands", "TC", "TCA"),
	TUV ("Tuvalu", "TV", "TUV"),
	VIR ("U.S. Virgin Islands", "VI", "VIR"),
	UGA ("Uganda", "UG", "UGA"),
	UKR ("Ukraine", "UA", "UKR"),
	ARE ("United Arab Emirates", "AE", "ARE"),
	GBR ("United Kingdom", "GB", "GBR"),
	USA ("United States", "US", "USA"),
	URY ("Uruguay", "UY", "URY"),
	UZB ("Uzbekistan", "UZ", "UZB"),
	VUT ("Vanuatu", "VU", "VUT"),
	VAT ("Vatican", "VA", "VAT"),
	VEN ("Venezuela", "VE", "VEN"),
	VNM ("Vietnam", "VN", "VNM"),
	WLF ("Wallis and Futuna", "WF", "WLF"),
	ESH ("Western Sahara", "EH", "ESH"),
	YEM ("Yemen", "YE", "YEM"),
	ZMB ("Zambia", "ZM", "ZMB"),
	ZWE ("Zimbabwe", "ZW", "ZWE");

	private String fullName;
	private String isoCode2;
	private String isoCode3;

	private Country (String fullName,
			String isoCode2,String isoCode3) {

		this.fullName = fullName;
		this.isoCode2 = isoCode2;
		this.isoCode3 = isoCode3;
	}
}
